name:                sudoku
version:             0.1.0.0
github:              "githubuser/sudoku"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

dependencies:
- base >= 4.7 && < 5
- QuickCheck
- hspec

library:
  source-dirs: src

executables:
  sudoku-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sudoku

tests:
  sudoku-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sudoku
